# Generated by Django 3.2 on 2022-04-06 18:33

from django.db import migrations, models
import link.models.banner


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to=link.models.banner.image_path)),
                ('url', models.CharField(blank=True, default='#/', max_length=260, null=True)),
                ('description', models.TextField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60)),
                ('full_name', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletişim',
                'verbose_name_plural': 'İletişim',
            },
        ),
        migrations.CreateModel(
            name='SocialLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Facebook'), ('2', 'Twitter'), ('3', 'Google'), ('4', 'Instagram'), ('5', 'Linkedin'), ('6', 'Pinterest'), ('7', 'Vkontakte'), ('8', 'Stack overflow'), ('9', 'Youtube'), ('10', 'Slack'), ('11', 'Github'), ('12', 'Dribbble'), ('13', 'Reddit')], max_length=2, unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Sosyal Ağ',
                'verbose_name_plural': 'Sosyal Ağlar',
            },
        ),
    ]
